### ISSUE TITLE
Release 1.2.4 - no OpenMP build ?

### ISSUE THREAD

**Issue by DTL2020** [Asd-g/AviSynth-vsTTempSmooth#11]
It looks like the OpenMP setting was missing in the compiler so release .dll do not have OpenMP support ? So threads param is not working (always run single threaded).

Also the current repository project files for VisualStudio do not have Open MP Support enabled for Release configuration.

OpenMP not throw any error from release build if not enabled but simply not working. Maybe some warning was at compiler output if openmp pragma exists but OpenMP is not enabled in compiler settings ? May be possible to somehow raise stop compiler error to not forget to enable this setting ?

This line looks missed - https://github.com/DTL2020/AviSynth-vsTTempSmooth/blob/a0317d95b77e6bf02206ea1c8c5b2dfa879f3259/build/vsTTempSmooth.vcxproj#L147

**Comment by Asd-g** [comment]
GCC detect OpenMP and add -fopenmp but MSVC like compilers doesn't.
