### ISSUE TITLE
Crash with strength=2

### ISSUE THREAD

**Issue by Dogway** [Asd-g/AviSynth-vsTTempSmooth#3]
Using DGSource or FFMS on a 1080p source I get a crash when using a `strength` of 2 with the following call:

`vsTTempSmooth(maxr=2,strength=2,fp=true,ythresh=255,scthresh=28,y=true,u=false,v=false)`

If I set strength to 1 or omit it it works though. I'm testing other combinations but avspmod takes 5 minutes to launch so it's slow.

Yes, 3 and 1 also crashes, so something is going on in there, looks like `strength` is not working at all.

`vsTTempSmooth(maxr=3,strength=1,fp=true,ythresh=255,scthresh=28,y=true,u=false,v=false)`

EDIT: no, it's just unstable, crashes at the second time I F5, even if not calling the filter.

**Comment by Asd-g** [comment]
Try 1.2.0.
