### ISSUE TITLE
Crash with field-based input (?)

### ISSUE THREAD

**Issue by DTL2020** [Asd-g/AviSynth-vsTTempSmooth#5]
Trying to use it as blending engine for RIFE with interlaced clip. If feed to RIFE and vsTTempSmooth() clip after SeparateFields:

Version 1.0.0 output only upper half of frame.
Version 1.2.0 and some previous - either access-violation string in VirtualDub status line (before 1.2.0) or VirtualDub dissapear (in latest 1.2.0).

If feed 'full frame' - everything is working.

Script with crash:
# Input plugins
LoadPlugin("RIFE.dll")
LoadPlugin("vsTTempSmooth.dll")

ColorBars(1920, 1080)
ConvertToYV12(interlaced=true)
SeparateFields()
src=last
ConvertToRGB()
ConvertToPlanarRGB()
ConvertBits(32)
tr1=RIFE(denoise=true, denoise_tr=1, sc=true, sc_threshold=0.05)
tr2=RIFE(denoise=true, denoise_tr=2, sc=true, sc_threshold=0.05)
tr1=ConvertToRGB24(tr1).ConvertToYV12()
tr2=ConvertToRGB24(tr2).ConvertToYV12()
Interleave(tr1, src, tr2)
vsTTempSmooth(maxr=2)
SelectEvery(3, 1)
Weave()
Prefetch(2)

Script without crash:
# Input plugins
LoadPlugin("RIFE.dll")
LoadPlugin("vsTTempSmooth.dll")

ColorBars(1920, 1080)
ConvertToYV12(interlaced=true)

#SeparateFields()

src=last
ConvertToRGB()
ConvertToPlanarRGB()
ConvertBits(32)
tr1=RIFE(denoise=true, denoise_tr=1, sc=true, sc_threshold=0.05)
tr2=RIFE(denoise=true, denoise_tr=2, sc=true, sc_threshold=0.05)
tr1=ConvertToRGB24(tr1).ConvertToYV12()
tr2=ConvertToRGB24(tr2).ConvertToYV12()
Interleave(tr1, src, tr2)
vsTTempSmooth(maxr=2)
SelectEvery(3, 1)

#Weave()

Prefetch(2)

only SeparateFields and Weave commented out. Other tested blending/temporal engines (Clense and MedianBlurTemporal) work correctly after RIFE. Only vsTTempSmooth produce crash somwhere. RIFE latest 1.0.3 used.

**Comment by Asd-g** [comment]
Try 1.2.1.

**Comment by DTL2020** [comment]
1.2.1 release works the same - crash with auto-closing of VirtualDub.

**Comment by Asd-g** [comment]
Redownload it and try again.

**Comment by DTL2020** [comment]
Now it work with separated fields content too. Thank you. May be issue may be closed. May be wait for other users to test.
