### ISSUE TITLE
Building x86 (32bit)

### ISSUE THREAD

**Issue by DTL2020** [Asd-g/AviSynth-vsTTempSmooth#9]
It looks the project was not tested or not compatible to build Win32 (x86 32bit) binary ?

First the project file for Visual Studio do not have C++17 setting for language (simple to set).

Next attempt to build Win32 release fails with same errors from all SIMD .cpp files:
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\ucrt\corecrt_math.h(749,37): error C2666: 'pow': 7 overloads have similar conversions (compiling source file ..\src\vsTTempSmooth_AVX2.cpp)
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\ucrt\corecrt_math.h(486,35): message : could be 'double pow(double,double)' (compiling source file ..\src\vsTTempSmooth_AVX2.cpp)

Is it some issue with VCL used ?

Tried with Win10, VisualStudio 2019 16.3.0 and Windows SDK version 10.0.20348.0

**Comment by Asd-g** [comment]
I dropped 32-bit plugins some time ago.

It's VCL related issue.
